#!/bin/sh
# Installs the ssh keys in the keys directory
# to the authorized_keys file for this user
# account on this machine.
LS=`which ls`
BASEDIR=$(dirname $0)
if [ ! -d ~/.ssh ]; then
	mkdir ~/.ssh
	chmod 0700 ~/.ssh
fi
for PUBKEY in `${LS} ${BASEDIR}/keys/*.pub`; do
	cat ${PUBKEY} >> ${BASEDIR}/authorized_keys
	chmod 0600 ${BASEDIR}/authorized_keys
done
